# Generated by Django 5.0.6 on 2024-05-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamburgueria.breadtype'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='carne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamburgueria.meattype'),
        ),
    ]
