# Generated by Django 5.0.6 on 2024-05-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0002_breadtype_meattype_pedido_notas_alter_pedido_pao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeatType',
            new_name='Carne',
        ),
        migrations.RenameModel(
            old_name='BreadType',
            new_name='Pao',
        ),
    ]
