# Generated by Django 5.0.6 on 2024-05-23 13:39

import hamburgueria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0003_rename_meattype_carne_rename_breadtype_pao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='opcionais',
            field=models.CharField(max_length=100, verbose_name=hamburgueria.models.Opcionais),
        ),
    ]
