# Generated by Django 5.0.6 on 2024-06-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0005_remove_pedido_opcionais_hamburguerpredefinido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HamburguerPredefinido',
        ),
    ]
